spring:
  application:
    name: csd

  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.tdhhdbipbnlfdjlbxege
    password: ${SUPABASE_SERVER_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      connection-init-sql: SET search_path TO public

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
    hibernate:
      ddl-auto: validate

    properties:
      '[format_sql]': true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        '[default_schema]': public

  