spring:
  application:
    name: csd

  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.tdhhdbipbnlfdjlbxege
    password: ${SUPABASE_SERVER_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      connection-init-sql: SET search_path TO public

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
    hibernate:
      ddl-auto: validate

    properties:
      '[format_sql]': true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        '[default_schema]': public

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://tdhhdbipbnlfdjlbxege.supabase.co/auth/v1
  
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: ${REDIS__SSL:false}
      timeout: 2s

supabase:
  jwt:
    secret: ${SUPABASE_JWT_SECRET}
  url: ${SUPABASE_URL}
  service:
    key: ${SUPABASE_SERVICE_KEY}
